### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by eroux** [France-ioi/graderqueue#1]
Bonjour, 

je travaille sur [TaskPlatform](https://github.com/France-ioi/TaskPlatform) et je voudrais commencer à pouvoir intégrer l'évaluation à travers graderqueue. Par contre je ne comprend pas tout à fait le workflow que je dois utiliser (quel fichier php appeler quand et avec quels paramètres), serait-il possible de le documenter ? Aussi je ne suis pas sûr de tout à fait comprendre le rôle du graderserver ? Enfin (moins urgent), s'il est possible d'avoir un fichier de conf pour nginx en plus d'apache ce serait super.

Merci !

**Comment by mblockelet** [comment]
Salut,

J'ai rajouté une documentation (README.md) qui devrait couvrir toutes tes questions. Par ailleurs, j'ai mis un fichier de configuration pour nginx dans le dossier `examples`; je n'ai pas encore pu le tester par contre.

**Comment by eroux** [comment]
Salut !

Merci beaucoup pour la doc et le fichier nginx! Quelques petites choses : 
- il y a une référence à un fichier htaccess dans le readme, mais il ne semble pas être là
- je comprend beaucoup mieux les appels mais je ne comprend toujours pas vraiment l'architecture : qu'est-ce que tu appelles "task" et "solution" par exemple ? qu'est-ce que ça comprend ? Est-ce que "task" ce serait par exemple une soumission d'un utilisateur ou plutôt un exo en général ? en fait voilà : est-ce que c'est une "task" du point de vue du grader qui a une tâche à faire, ou est-ce que c'est une "task" dans le sens un exercice ?

Merci !

**Comment by mblockelet** [comment]
Salut !
- En effet, j'avais oublié de commit le fichier htaccess d'exemple...
- C'est vrai que ce n'est pas très clair, surtout pour les "tasks" vu que même au niveau du graderqueue il y a un endroit où "task" n'a pas la même signification... En général, quand on parle de "task", c'est au sens du graderqueue, donc une "tâche à faire par le grader". Le seul endroit que je vois où ça parle de "task" au sens d'exercice, c'est quand ça parle de "task path", où ça correspond au chemin de l'exercice. Je vais réfléchir à une façon de rendre cette différence plus claire.

**Comment by eroux** [comment]
Merci ! J'ai installé taskgrader et graderqueue, ça a l'air de fonctionner (modulo les deux mini pull requests). Ce que je ne comprend encore pas c'est comment concrètement ça se passe, imaginons:
- un élève a son navigateur qui point vers un exo et soumet une réponse, la plateforme générale est ok pour l'évaluer, du coup l'exo va vouloir envoyer la soumission de l'élève au graderqueue
- si je comprend bien, ça ne peut pas se faire en javascript directement, il faut que le navigateur appelle une sorte de proxy de graderqueue en php, qui lui va faire des requêtes curl vers graderqueue/api.php avec le certificat généré par cert/genclientcert.sh ?

Si c'est bien ça, je me dis que ça pourrait peut-être être un peu simplifié en faisant que le navigateur de l'élève envie le json dans un [JWT](http://jwt.io/) signé avec la clé privée de la platforme d'exos, et faire que graderqueue n'accepte que les tokens qui peuvent être déchiffrés par les clés publique qui sont dans la table _platforms_ ? Ce serait plus simple à mettre en place et ce serait uniforme avec le reste du système qui fonctionne de cette façon.

**Comment by eroux** [comment]
Je prépare une branche "jws" avec les deux changements dont a parlé Mathias dans le mail, dis-moi si ça te va

**Comment by mblockelet** [comment]
Tu as bien compris le fonctionnement actuel; pas de soucis pour JWT, je ne connais pas trop mais si c'est plus simple pourquoi pas !
