### ISSUE TITLE
tests pour wakeupurl

### ISSUE THREAD

**Issue by eroux** [France-ioi/graderqueue#5]
Ce serait pratique de pouvoir tester la wakeup_url, j'ai fait un petit truc, mais j'arrive vraiment pas à faire fonctionner la wakeup-url... j'ai cherché un peu partout, mais je vais attendre que tu puisses faire un petit truc pour que je teste, qui puisse diagnostiquer où pourrait se situer le problème...

**Comment by eroux** [comment]
En fait je crois qu'il faudrait que le mieux serait que graderserver renvoie un petit truc genre "ok" et qu'il y ait une gestion des erreurs

**Comment by mblockelet** [comment]
Fixed in 78925a233b4f37a86ef87b86ad36346a2e4d134d.
